### ISSUE TITLE
program not found

### ISSUE THREAD

**Issue by advanxer** [bmachek/tp-link-cmk#1]
When i execute this check, it returned me this error "ERROR [agent]: Program 'tp-link-power.js' not found (exit code 127)(!!)"
I have verified that the program is installed in the correct path:
OMD[home]:~/local/bin$ ls
tp-link-power.js*

and correct permission with chmod +x:
-rwxr-xr-x 1 home home  586 Feb 25 17:48 tp-link-power.js*

I installed this plugin from check_mk exchange.

**Comment by advanxer** [comment]
i have fixed it, its due to missing nodejs and tp-link API. I created simple documentation here, https://advanxer.com/blog/2019/04/monitor-tp-link-smart-plug-in-check_mk/

Thanks for this plugin :)

**Comment by bmachek** [comment]
Thank you for fixing and documenting this! :-)
